apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: https://gcr.io/fiery-odyssey-230213/github.com/chris-henry-oxford/frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
